### ISSUE TITLE
Failed to install.

### ISSUE THREAD

**Issue by willnaoosmith** [florindumitru/react-native-sip#4]
error C:\Users\XXX\Desktop\AwesomeProject\node_modules\react-native-sip: Command failed.
Exit code: 1
Command: bash libs.sh

I'm trying to compile it on windows 10 x64, and dont have any linux machine to compile it now.
The problem it's on package.json who invokes "postinstall": "bash libs.sh". and libs.sh only download from github the latest version of the old repository of Datso (React-native-pjsip).
Can you remove this post install line?

**Comment by willnaoosmith** [comment]
I run with npm install --ignore-scripts and solved this.

**Comment by mofolo** [comment]
I found that I had the same issue because I did not have Docker installed on my machine.
Once docker was installed and running the script ran perfectly - it took some time to install as it had to download the Android SDK etc, and compile a whole bunch of stuff (approx 30 minutes).

If you're using Yarn there is no information about progress, it just looks like it's "waiting".

Note that NPM is still on version 2.8.0 and this does not compile, you **must** use yarn to install this package
